// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: countPores.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CountPoresRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Extenstion string `protobuf:"bytes,1,opt,name=extenstion,proto3" json:"extenstion,omitempty"`
	Height     int32  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Width      int32  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Image      []byte `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Density    int32  `protobuf:"varint,5,opt,name=density,proto3" json:"density,omitempty"`
}

func (x *CountPoresRequest) Reset() {
	*x = CountPoresRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_countPores_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountPoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountPoresRequest) ProtoMessage() {}

func (x *CountPoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_countPores_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountPoresRequest.ProtoReflect.Descriptor instead.
func (*CountPoresRequest) Descriptor() ([]byte, []int) {
	return file_countPores_proto_rawDescGZIP(), []int{0}
}

func (x *CountPoresRequest) GetExtenstion() string {
	if x != nil {
		return x.Extenstion
	}
	return ""
}

func (x *CountPoresRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CountPoresRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CountPoresRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *CountPoresRequest) GetDensity() int32 {
	if x != nil {
		return x.Density
	}
	return 0
}

type CountPoresResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area     float32 `protobuf:"fixed32,1,opt,name=area,proto3" json:"area,omitempty"`
	Diameter float32 `protobuf:"fixed32,2,opt,name=diameter,proto3" json:"diameter,omitempty"`
}

func (x *CountPoresResponse) Reset() {
	*x = CountPoresResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_countPores_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountPoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountPoresResponse) ProtoMessage() {}

func (x *CountPoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_countPores_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountPoresResponse.ProtoReflect.Descriptor instead.
func (*CountPoresResponse) Descriptor() ([]byte, []int) {
	return file_countPores_proto_rawDescGZIP(), []int{1}
}

func (x *CountPoresResponse) GetArea() float32 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *CountPoresResponse) GetDiameter() float32 {
	if x != nil {
		return x.Diameter
	}
	return 0
}

var File_countPores_proto protoreflect.FileDescriptor

var file_countPores_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x91, 0x01, 0x0a, 0x11, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x6f, 0x72, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x74, 0x65,
	0x6e, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78,
	0x74, 0x65, 0x6e, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64,
	0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x22, 0x44, 0x0a, 0x12, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x50,
	0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x72, 0x65, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x08, 0x64, 0x69, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x32, 0x40, 0x0a, 0x0a,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x05, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x6f, 0x72, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x50,
	0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_countPores_proto_rawDescOnce sync.Once
	file_countPores_proto_rawDescData = file_countPores_proto_rawDesc
)

func file_countPores_proto_rawDescGZIP() []byte {
	file_countPores_proto_rawDescOnce.Do(func() {
		file_countPores_proto_rawDescData = protoimpl.X.CompressGZIP(file_countPores_proto_rawDescData)
	})
	return file_countPores_proto_rawDescData
}

var file_countPores_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_countPores_proto_goTypes = []interface{}{
	(*CountPoresRequest)(nil),  // 0: CountPoresRequest
	(*CountPoresResponse)(nil), // 1: CountPoresResponse
}
var file_countPores_proto_depIdxs = []int32{
	0, // 0: CountPores.Count:input_type -> CountPoresRequest
	1, // 1: CountPores.Count:output_type -> CountPoresResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_countPores_proto_init() }
func file_countPores_proto_init() {
	if File_countPores_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_countPores_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountPoresRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_countPores_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountPoresResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_countPores_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_countPores_proto_goTypes,
		DependencyIndexes: file_countPores_proto_depIdxs,
		MessageInfos:      file_countPores_proto_msgTypes,
	}.Build()
	File_countPores_proto = out.File
	file_countPores_proto_rawDesc = nil
	file_countPores_proto_goTypes = nil
	file_countPores_proto_depIdxs = nil
}
