# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: countPores.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ountPores.proto\"f\n\x11\x43ountPoresRequest\x12\x12\n\nextenstion\x18\x01 \x01(\t\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\r\n\x05image\x18\x04 \x01(\x0c\x12\x0f\n\x07\x64\x65nsity\x18\x05 \x01(\x05\"4\n\x12\x43ountPoresResponse\x12\x0c\n\x04\x61rea\x18\x01 \x01(\x02\x12\x10\n\x08\x64iameter\x18\x02 \x01(\x02\x32@\n\nCountPores\x12\x32\n\x05\x43ount\x12\x12.CountPoresRequest\x1a\x13.CountPoresResponse\"\x00\x42\tZ\x07./grpc/b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'countPores_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007./grpc/'
  _COUNTPORESREQUEST._serialized_start=20
  _COUNTPORESREQUEST._serialized_end=122
  _COUNTPORESRESPONSE._serialized_start=124
  _COUNTPORESRESPONSE._serialized_end=176
  _COUNTPORES._serialized_start=178
  _COUNTPORES._serialized_end=242
# @@protoc_insertion_point(module_scope)
