# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lesionSegmentation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18lesionSegmentation.proto\"X\n\x14SegmentLesionRequest\x12\x12\n\nextenstion\x18\x01 \x01(\t\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\r\n\x05image\x18\x04 \x01(\x0c\"/\n\x15SegmentLesionResponse\x12\x16\n\x0esegmentedImage\x18\x01 \x01(\x0c\x32P\n\x12LesionSegmentation\x12:\n\x07Segment\x12\x15.SegmentLesionRequest\x1a\x16.SegmentLesionResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lesionSegmentation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEGMENTLESIONREQUEST._serialized_start=28
  _SEGMENTLESIONREQUEST._serialized_end=116
  _SEGMENTLESIONRESPONSE._serialized_start=118
  _SEGMENTLESIONRESPONSE._serialized_end=165
  _LESIONSEGMENTATION._serialized_start=167
  _LESIONSEGMENTATION._serialized_end=247
# @@protoc_insertion_point(module_scope)
