# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lesionSegmentation_pb2 as lesionSegmentation__pb2


class LesionSegmentationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Segment = channel.unary_unary(
                '/LesionSegmentation/Segment',
                request_serializer=lesionSegmentation__pb2.SegmentLesionRequest.SerializeToString,
                response_deserializer=lesionSegmentation__pb2.SegmentLesionResponse.FromString,
                )


class LesionSegmentationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Segment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LesionSegmentationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Segment': grpc.unary_unary_rpc_method_handler(
                    servicer.Segment,
                    request_deserializer=lesionSegmentation__pb2.SegmentLesionRequest.FromString,
                    response_serializer=lesionSegmentation__pb2.SegmentLesionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LesionSegmentation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LesionSegmentation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Segment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LesionSegmentation/Segment',
            lesionSegmentation__pb2.SegmentLesionRequest.SerializeToString,
            lesionSegmentation__pb2.SegmentLesionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
