# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_pb2 as image__pb2


class ClassificateImageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Classificate = channel.unary_unary(
                '/ClassificateImage/Classificate',
                request_serializer=image__pb2.ImageClassificationRequest.SerializeToString,
                response_deserializer=image__pb2.ImageClassificationResponse.FromString,
                )


class ClassificateImageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Classificate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClassificateImageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Classificate': grpc.unary_unary_rpc_method_handler(
                    servicer.Classificate,
                    request_deserializer=image__pb2.ImageClassificationRequest.FromString,
                    response_serializer=image__pb2.ImageClassificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ClassificateImage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClassificateImage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Classificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClassificateImage/Classificate',
            image__pb2.ImageClassificationRequest.SerializeToString,
            image__pb2.ImageClassificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
