# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\"^\n\x1aImageClassificationRequest\x12\x12\n\nextenstion\x18\x01 \x01(\t\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\r\n\x05image\x18\x04 \x01(\x0c\"2\n\x1bImageClassificationResponse\x12\x13\n\x0b\x44iseaseName\x18\x01 \x01(\t2`\n\x11\x43lassificateImage\x12K\n\x0c\x43lassificate\x12\x1b.ImageClassificationRequest\x1a\x1c.ImageClassificationResponse\"\x00\x42\tZ\x07./grpc/b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007./grpc/'
  _IMAGECLASSIFICATIONREQUEST._serialized_start=15
  _IMAGECLASSIFICATIONREQUEST._serialized_end=109
  _IMAGECLASSIFICATIONRESPONSE._serialized_start=111
  _IMAGECLASSIFICATIONRESPONSE._serialized_end=161
  _CLASSIFICATEIMAGE._serialized_start=163
  _CLASSIFICATEIMAGE._serialized_end=259
# @@protoc_insertion_point(module_scope)
